[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~3.3.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"


[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "gopkg.in/gorp.v2"
  version = "2.1.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"
