[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~3.3.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

